version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/data
      - /data/node_modules
    ports:
      - 27081:80
    container_name: wxcloud_yuboshu
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=yuboshu
      - role=container
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
networks:
  default:
    external:
      name: wxcb0
